[book]
authors = ["../AUTHORS.md"]
language = "en"
multilingual = false
src = "src"
title = "ri2p Documentation"

[output.html]
git-repository-url = "https://github.com/ChristopherBilg/ri2p"
edit-url-template = "https://github.com/ChristopherBilg/ri2p/edit/master/docs/{path}"
site-url = "/ri2p/"
cname = "ri2p.com"
