name: mdBook

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Build mdBook and cargo docs
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - run: |
          mdbook build docs/
          cargo doc --target-dir ./docs/book/doc
      - name: Deploy mdBook and cargo doc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/book
